### ISSUE TITLE
Claiming land in Scarcy Skies crashes the Server

### ISSUE THREAD

**Issue by MrRubberDucky** [SattesKrokodil/Adventure-Pack#10]
**Describe the bug**
Trying to claim land in Scarcy Skies from [Starry Skies](https://www.curseforge.com/minecraft/mc-mods/starry-skies) with Golden Hoe [(Flan)](https://www.curseforge.com/minecraft/mc-mods/flan) makes server jump into a endless void

**To Reproduce**
1. Go to Scarcy Skies
2. Find a nice sphere
3. Try to claim it

**Expected behavior**
Land is claimed and server doesn't go bye-bye.

**Desktop (please complete the following information):**
 - Launcher: MultiMC
 - Version: AP 4.3.1
 - OS: Win10 1909
 - Official AP Server
 
**Additional context**
rock candy spheres

**Comment by SattesKrokodil** [comment]
should be fixed with latest flan!

**Comment by SattesKrokodil** [comment]
due to many issues with the portal API that's used by starry sky and the imbalance the mod causes in combination with the new age of exile progression system, I removed the mod. Still one of the coolest dimension mods in my opinion and it should be perfectly fine in singleplayer/smaller servers but I don't like crashes
