### ISSUE TITLE
Ability to upgrade dust tier

### ISSUE THREAD

**Issue by Esjitu** [SattesKrokodil/Adventure-Pack#25]
Was thinking about how you can upgrade the quality of a lot of other low-level AoE items such as combining chipped gems into better ones, or combining loot chests with upgrade orbs to increase their rarity, and so on. But there is no way to do this with salvage dust. It'd be awesome if I could put my chest full of t0 dust to use by turning it into t1 dust, then t1 to t2, and so on just like you can with gems and loot chests and such by using upgrade items. If the rarity of the upgrade items isn't enough to balance this system it could take more t0 dust to make less t1 dust, so it wouldn't be a cheap and easy replacement for salvaging higher tier items or anything, but it would still be a good way to get rid of the surplus of lower level dust you naturally find on your travels for just a little bit of extra.

**Comment by SattesKrokodil** [comment]
no it won't be a feature ever, dust (now essence) is basically the currency of AP and will be used as such for shops too. Making it upgradeable would only cause level 50 players farm low(-ish) level areas to get higher essence faster where they actually should put in some more effort to gather it. Also professions now (I know they weren't a thing when this issue was openend) make use of any essence.
